#! /bin/bash

. $(dirname $0)/run-all.include

default_src=Main.c
src=$1
if [ -z ${src} ] || [ ! -f ${src} ]; then
	src=${default_src}
fi

function _init_src() {
	if [ -f ${default_src} ]; then
		echo "${default_src}: File already exists."
		return 1
	fi
	cat <<__EOF__ > ${default_src}
#include <stdio.h>

int main(int argc, char** argv) {
	return 0;
}
__EOF__
	return 0
}
function _compile() {
	if [ "$(dirname ${src})" != "." ]; then
		gcc -std=gnu11 -O2 -o a.out $(find $(dirname ${src}) -name '*.c') -lm ${L}
	else
		gcc -std=gnu11 -O2 -o a.out ${src} -lm ${L}
	fi
}
_cmd="./a.out"

. $(dirname $0)/run-all.base
