#! /bin/bash

. $(dirname $0)/run-all.include

default_src=Main.go
src=$1
if [ -z ${src} ] || [ ! -f ${src} ]; then
	src=${default_src}
fi

function _init_src() {
	if [ -f ${default_src} ]; then
		echo "${default_src}: File already exists."
		return 1
	fi
	cat <<__EOF__ > ${default_src}
package main

import (
        "bufio"
        "io"
        "os"
        "strconv"
)

func main() {
        stdin := bufio.NewReader(os.Stdin)
        stdout := bufio.NewWriter(os.Stdout)
}
__EOF__
	return 0
}
if [ ! -v bin_path ]; then
	bin_path=go
fi

function _compile() {
	local dataDir=$(pwd)
	cd ${_src_dir}
	GOPATH=${dataDir} ${bin_path} build ${src}
	s=$?
	cd ${dataDir}
	return ${s}
}

_src_dir=$(dirname ${src})
src=$(basename ${src})
_cmd="./$(basename ${src} .go)"

. $(dirname $0)/run-all.base
